//
//  BreedListRouter.swift
//  Clean Doggo
//
//  Created by Jovan Radivojsa on 9/30/18.
//  Copyright (c) 2018 Jovan Radivojsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BreedListRoutingNavigation {
    func showNewScreen()
}

protocol BreedListDataPassing {
    var dataStore: BreedListDataStore? { get set }
    func passDataToNextScene(segue: UIStoryboardSegue)
}

typealias BreedListRouterInput = BreedListRoutingNavigation & BreedListDataPassing

class BreedListRouter: BreedListRouterInput {
    
    private struct Segues {
        static let ShowNextScreenIdentifier = ""
    }
    
    var dataStore: BreedListDataStore?
    weak var viewController: BreedListViewController?
    
    // MARK: Navigation
    
    func showNewScreen() {
        viewController?.performSegue(withIdentifier: Segues.ShowNextScreenIdentifier, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        if segue.identifier == Segues.ShowNextScreenIdentifier {
            // Pass Relevant Data
        }
    }
}
