//
//  BreedListInteractor.swift
//  Clean Doggo
//
//  Created by Jovan Radivojsa on 9/30/18.
//  Copyright (c) 2018 Jovan Radivojsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BreedListBusinessLogic {
    func doSomething(_ request: BreedList.Something.Request)
}

protocol BreedListDataStore {
    //var name: String { get set }
}

class BreedListInteractor: BreedListBusinessLogic, BreedListDataStore {
    
    var presenter: BreedListPresentationLogic?
    lazy var worker: BreedListWorker? = {
        return BreedListWorker()
    }()
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(_ request: BreedList.Something.Request) {
        worker?.doSomeWork()
        
        let response = BreedList.Something.Response()
        presenter?.presentSomething(response)
    }
}
