//
//  BreedListConfigurator.swift
//  Clean Doggo
//
//  Created by Jovan Radivojsa on 9/30/18.
//  Copyright (c) 2018 Jovan Radivojsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

extension BreedListViewController {
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(segue: segue)
    }
}

// MARK: - Connects View, Interactor, and Presenter
class BreedListConfigurator {
    
    static let sharedInstance = BreedListConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(_ viewController: BreedListViewController) {
        let presenter = BreedListPresenter()
        presenter.viewController = viewController
        
        let interactor = BreedListInteractor()
        interactor.presenter = presenter
        
        let router = BreedListRouter()
        router.viewController = viewController
        router.dataStore = interactor
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
