//
//  BreedListWorker.swift
//  Clean Doggo
//
//  Created by Jovan Radivojsa on 9/30/18.
//  Copyright (c) 2018 Jovan Radivojsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BreedListWorker {
    
    func doSomeWork() {
    }
}
